CREATE TABLE products	 (
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
     name CHAR(30) NOT NULL,
     description VARCHAR(255) NOT NULL,
     PRIMARY KEY (id)
);

CREATE TABLE reviews (
	id MEDIUMINT NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	text VARCHAR(500) NOT NULL,
	created_by VARCHAR(255) NOT NULL,
	product_id MEDIUMINT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (product_id) REFERENCES PRODUCTS(id)
);

CREATE TABLE comments (
	id MEDIUMINT NOT NULL AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	text VARCHAR(500) NOT NULL,
	created_by VARCHAR(255) NOT NULL,
	review_id MEDIUMINT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (review_id) REFERENCES REVIEWS(id)
);
